.PHONY: clean All

All:
	@echo "----------Building project:[ smart_ptr - Debug ]----------"
	@cd "smart_ptr" && "$(MAKE)" -f  "smart_ptr.mk"
clean:
	@echo "----------Cleaning project:[ smart_ptr - Debug ]----------"
	@cd "smart_ptr" && "$(MAKE)" -f  "smart_ptr.mk" clean
