.PHONY: clean All

All:
	@echo "----------Building project:[ Playlist - Debug ]----------"
	@cd "Playlist" && "$(MAKE)" -f  "Playlist.mk"
clean:
	@echo "----------Cleaning project:[ Playlist - Debug ]----------"
	@cd "Playlist" && "$(MAKE)" -f  "Playlist.mk" clean
