.PHONY: clean All

All:
	@echo "----------Building project:[ Polymorphism - Debug ]----------"
	@cd "C:\Users\admin\Desktop\c++basics\Polymorphism\Polymorphism_basic" && "$(MAKE)" -f  "Polymorphism.mk"
clean:
	@echo "----------Cleaning project:[ Polymorphism - Debug ]----------"
	@cd "C:\Users\admin\Desktop\c++basics\Polymorphism\Polymorphism_basic" && "$(MAKE)" -f  "Polymorphism.mk" clean
